export const posts = [
    {
      _id: "6574a89c7432fef75c2f664d",
      nom: "logtari",
      prenom: "yassine",
      email: "logtari@gmail.com",
      sexe: "Homme",
      dateNaissance: "31-07-2000",
      nationalite: "tunisien",
      CIN: "11457896",
      situationPerso: "célebataire",
      connaissanceMusic: false,
      activite: false,
      telephone: "20123456",
      role: "admin",
      statut: "Inactif",
    },
    {
      // id: 2,
      // username: "monica",
      // fullname: "Monica Stan",
      // userImg:
      //   "https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      // postImg:
      //   "https://images.pexels.com/photos/3497624/pexels-photo-3497624.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
      _id: "657f335e2bf5da651901f5a7",
      nom: "boumaiza",
      prenom: "siwar",
      email: "siwarboumaiza2@gmail.com",
      sexe: "Femme",
      dateNaissance: "05-07-2000",
      nationalite: "tunisienne",
      CIN: "15120418",
      situationPerso: "célebataire",
      connaissanceMusic: false,
      activite: false,
      telephone: "20123456",
      role: "chef du pupitre",
      statut: "En congé",
      pupitre: "alto"
    },
    {_id:"6574a8dd7432fef75c2f664e",
    nom: "ben salah",
    prenom: "sadak",
    email: "sadak@gmail.com",
    sexe: "Homme",
    dateNaissance: "01-05-2000",
    nationalite: "tunisien",
    CIN: "14121578",
    situationPerso: "célebataire",
    connaissanceMusic: false,
    activite: false,
    telephone: "20147183",
    role: "choriste",
    statut: "Inactif"
  }
  ];