// export const posts = [
//     {
//       _id: "6574a89c7432fef75c2f664d",
//       nom: "logtari",
//       prenom: "yassine",
//       email: "logtari@gmail.com",
//       sexe: "Homme",
//       dateNaissance: "31-07-2000",
//       nationalite: "tunisien",
//       CIN: "11457896",
//       situationPerso: "célebataire",
//       connaissanceMusic: false,
//       activite: false,
//       telephone: "20123456",
//       role: "admin",
//       statut: "Inactif",
//     },
//     {
     
//       _id: "6589d9ee197c4d607b91e3d9",
//       nom: "boumaiza",
//       prenom: "siwar",
//       email: "siwarboumaiza2@gmail.com",
//       sexe: "Femme",
//       dateNaissance: "05-07-2000",
//       nationalite: "tunisienne",
//       CIN: "15120418",
//       situationPerso: "célebataire",
//       connaissanceMusic: false,
//       activite: false,
//       telephone: "20123456",
//       role: "chef du pupitre",
//       statut: "En congé",
//       pupitre: "alto"
//     },
//     {_id:"6574a8dd7432fef75c2f664e",
//     nom: "ben salah",
//     prenom: "sadak",
//     email: "sadak@gmail.com",
//     sexe: "Homme",
//     dateNaissance: "01-05-2000",
//     nationalite: "tunisien",
//     CIN: "14121578",
//     situationPerso: "célebataire",
//     connaissanceMusic: false,
//     activite: false,
//     telephone: "20147183",
//     role: "choriste",
//     statut: "Inactif"
//   },
//   {
//     _id: "65847a047432fef75c2f670b",
//     nom: "benrjeb",
//     prenom: "kamel",
//     email: "kamel@gmail.com",
//     sexe: "Homme",
//     dateNaissance: "27-06-1969",
//     nationalite: "tunisien",
//     CIN: "14021789",
//     situationPerso: "célebataire",
//     connaissanceMusic: false,
//     activite: false,
//     telephone: "25146789",
//     role: "admin",
//     statut: "Inactif"
   
//   },
//   {
//     _id:"657c80e32959073c5357181e",
//     nom: "log",
//     prenom: "youss",
//     email: "youssef@gmail.com",
//     sexe: "Homme",
//     dateNaissance: "01-05-2000",
//     nationalite: "tunisien",
//     CIN: "89562314",
//     situationPerso: "célebataire",
//     connaissanceMusic: false,
//     activite: false,
//     telephone: "20147183",
//     role: "choriste",
//     statut: "En congé",
//     pupitre: "alto"
    
//   },

//   {
//     _id: "657ef32709dc45ec24808f1e",
//     nom: "ounissi",
//     prenom: "mohamed",
//     email: "ounissilol@gmail.com",
//     sexe: "Homme",
//     dateNaissance: "03-11-1998",
//     nationalite: "tunisien",
//     CIN: "11457896",
//     situationPerso: "célebataire",
//     connaissanceMusic: false,
//     activite: false,
//     telephone: "20123456",
//     role: "choriste",
//     statut: "Inactif",
//     pupitre: "alto"
//   },
//   ];